name: Nuke Certs
on:
  workflow_dispatch:

jobs:
  nuke_certs_job:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Bundler
        run: gem install bundler

      - name: Update Bundler and Fastlane
        run: |
          bundle install
          bundle update fastlane

      - name: Nuke Certs
        run: bundle exec fastlane nuke_certs
